services:
  db:
    container_name: postgres_cont
    image: postgres:15
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_cont
    image: dpage/pgadmin4:7.0
    restart: always
    env_file:
      - ../.env
    ports:
      - "8080:80"
    depends_on:
      - db

  python:
    container_name: python_cont
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/analisis-de-bolsa

  scraper:
    container_name: scraper_cont
    build:
      context: ..
      dockerfile: docker/scraper.Dockerfile
    volumes:
      - ../scraper/scrap_data:/scraper/scrap_data
      - ../scraper/lecap_scrap.py:/scraper/lecap_scrap.py
    restart: no
volumes:
  pgdata: